### ISSUE TITLE
Type-safer parser: use `vapply()` instead of `sapply()`

### ISSUE THREAD

**Issue by philipp-baumann** [pierreroudier/opusreader#10]
[`opus_read_raw()`](https://github.com/pierreroudier/opusreader/blob/main/R/opus_read_raw.R)
e.g. l. 119
`sapply()` is for interactive use; use `vapply()` and supply `FUN.VALUE` with expected type; for example `FUN.VALUE = character(1)`. Could also bring some minimal speed improvements.

**Comment by pierreroudier** [comment]
Fixed in https://github.com/pierreroudier/opusreader/commit/259abc839d3405def6f6715d5ca49b5f8788b808
