### ISSUE TITLE
Query file size prior to allocating #bytes in the byte stream

### ISSUE THREAD

**Issue by philipp-baumann** [pierreroudier/opusreader#20]
Hi Pierre,
this is sort of a todo to briefly implement file size checks as you have suggested. I've hit the current max. size while reading a new set of approximately 1200 spectra.
Will address soon, this is just for the note taking.
Cheers!

**Comment by pierreroudier** [comment]
Commit https://github.com/pierreroudier/opusreader/commit/c999514bbfea4c0c981d53a489025050380a231a dynamically allocates memory based on file size. I think it fixes this issue, but feel free to re-open if I misunderstood your query.
