### ISSUE TITLE
opus_read fails to read a file while opus_read_raw succeeds

### ISSUE THREAD

**Issue by davidbenncsiro** [pierreroudier/opusreader#21]
For a particular .0 file, I see the following error from `opus_read`:
~~~
> names(opusreader::opus_read(path))
Error in HUM_rel[[1]] : subscript out of bounds
~~~
while `opus_read_raw` succeeds:
~~~
rw <- readBin(con = path, what = "raw", n = file.info(path)$size)
> names(opus_read_raw(rw))
 [1] "metadata"              "spec"                  "spec_no_atm_comp"      "sc_sample"             "sc_ref"                "ig_sample"            
 [7] "ig_ref"                "wavenumbers"           "wavenumbers_sc_sample" "wavenumbers_sc_ref" 
~~~
I should be able to provide you with the offending file as an attachment but will check with my collaborators at CSIRO first with whom you have recently spoken I think.

Note that the failure occurs under both Windows and Linux.

The good news is that `opus_read_raw` works under both Windows and Linux, where `simplerspec` failed under Linux. The existence of `opusreader` comes at a good time. Thanks.

**Comment by pierreroudier** [comment]
Hey @davidbenncsiro , thanks for pointing this issue out.

I don't think either @philipp-baumann or myself have encountered this one before, so it would be very helpful for us to have access to the `.0` file, for debugging purposes. This of course can be done via email if preferred. 

The bug itself is surprising given `opus_read` is obviously just a wrapper around `opus_read_raw`, but this also means I'm hopeful the fix might not require us to go too deep in the binary content of the file. 

Specifically, this might be an issue with the way the size of the file (option `n` in `readBin`) is set by `opus_read`.

**Comment by pierreroudier** [comment]
@davidbenncsiro Further to this, I have just pushed a new commit to test if the issue is with that `n` option. So you could try and reinstall the latest development version (`remotes::install_github("pierreroudier/opusreader")`), and see if that works.

**Comment by dbenn** [comment]
Thanks @pierreroudier. That fixes it and is consistent with the way I call `readBin()` to get the raw data to pass to `opus_read_raw()`, although your use of `file.size(path)` is even more brief than `file.info(path)$size`.

The only thing I notice is that whereas my failing unit test expected 19 metadata list items, only 18 are now returned. If you can't reproduce that with one of your own test files, I'll get mine to you.

**Comment by pierreroudier** [comment]
Excellent, thanks for checking @dbenn. 

> The only thing I notice is that whereas my failing unit test expected 19 metadata list items, only 18 are now returned. If you can't reproduce that with one of your own test files, I'll get mine to you.

On that point, are you able to tell me what is the piece of metadata missing?

**Comment by davidbenncsiro** [comment]
The test only checked the metadata list length not content and I don't have a before and after list.

Perhaps a comparison between `simplerspec` and `opusreader` could help us here?
~~~
> r1 <- opusreader::opus_read(soilspec.format::bruker.opus.binary.file.path())
> names(r1$metadata) 
[1] "unique_id"        "sample_id"        "date_time_sm"     "date_time_rf"     "sample_name"      "instr_name_range" "resolution_wn"
[8] "result_spc"       "beamspl"          "laser_wn"         "spc_in_file"      "zero_filling"     "temp_scanner_sm"  "temp_scanner_rf" 
[15] "hum_rel_sm"       "hum_rel_rf"       "hum_abs_sm"       "hum_abs_rf"
~~~
~~~
> r2 <- simplerspec::read_opus_bin_univ(soilspec.format::bruker.opus.binary.file.path())
> names(r2$metadata) 
[1] "unique_id"        "file_id"          "sample_id"        "rep_no"           "date_time_sm"     "date_time_rf"     "sample_name"
[8] "instr_name_range" "resolution_wn"    "... <- NULL"      "beamspl"          "laser_wn"         "spc_in_file"      "zero_filling"
[15] "temp_scanner_sm"  "temp_scanner_rf"  "hum_rel_sm"       "hum_rel_rf"       "hum_abs_sm"       "hum_abs_rf"
~~~
The differences are `"... <- NULL"` and `rep_no`. Omitting the first seems reasonable.

**Comment by davidbenncsiro** [comment]
Here's the zipped test file @pierreroudier: [example.zip](https://github.com/pierreroudier/opusreader/files/7308935/example.zip). I checked with Brendan that he's happy for this to be shared.

**Comment by pierreroudier** [comment]
@davidbenncsiro 

`opusreader` is largely just a re-factoring and packaging of @philipp-baumann's excellent `simplerspec`. 

There are a few things we changed when re-factoring the metadata extraction:

- `"... <- NULL` is stored in the `result_spc` of an `opusreader` output. It describes in which mode the spectrometer was used; such as `"AB'` (absorbance). 
- `rep_no` was a bit of metadata that was de-commisioned during the refactoring. The reason was because it was essentially too dependent on the sample naming convention, if I remember correctly.
