### ISSUE TITLE
Concatenating spectra with the `simple` option

### ISSUE THREAD

**Issue by pierreroudier** [pierreroudier/opusreader#3]
[This commit](https://github.com/pierreroudier/opusreader/commit/60e5e51af789ec00c726547ae617c39ce51a56e7) implements the new `simple` option. 

This option is pretty much only aimed to be used when reading a bunch of spectra all at once:

```
spec <- opus_read(file = c("file1.0", "file2.0", "file3.0"), simple = TRUE)
```

A boring reproducible example using the file contained in the package:

```
library(opusreader)

spec <- opus_read(file = rep(opus_file(), times = 20), simple = TRUE)
```

It returns a much simpler list:

- `wavenumbers`, which is a numeric vector of wavenumbers
- `spectra`, which is a matrix corresponding to the type of spectra specified using the `extract` option.

It becomes super easy to plot/analyse:

```
matplot(spec$wavenumbers, t(spec$spectra), type = "l", lty = 1)
```

**It seems the exact value of the wavenumbers vary from file to file**. At the moment, `wavenumber` is taken as the rounding of the wavenumbers of the first file read.

Is that an acceptable behaviour?

**Comment by philipp-baumann** [comment]
I like the simple type of option. What about renam `simplify`? 

> It seems the exact value of the wavenumbers vary from file to file. At the moment, wavenumber is taken as the rounding of the wavenumbers of the first file read.

Yes, guess because of wavenumber calibration, resolution, and stuff. We should signal an informative error. Yes, checking all and comparing to the wavenumbers of the first is reasonable.

**Comment by pierreroudier** [comment]
> I like the simple type of option. What about renam `simplify`?
>

Good suggetsion.
 
> Yes, guess because of wavenumber calibration, resolution, and stuff. We should signal an informative error. Yes, checking all and comparing to the wavenumbers of the first is reasonable.

OK -- but as one will concatenate those spectra into a matrix anyway for any further modelling anyway, do we actually throw an error? Maybe a warning is enough as folks need that step done anyway?

**Comment by pierreroudier** [comment]
[This commit](https://github.com/pierreroudier/opusreader/commit/7ed63f93fab2d4ca84e40c20a9c17de1dbdf54c9) implements your renaming suggestion.

**Comment by philipp-baumann** [comment]
Sounds good, thanks for the renaming commit.

The initial idea why I included the `wavenumbers` vector was because it's not really straightforward to deal with them only as column names of matrices and data.frames. What's the rationale behind rounding wavenumbers when `simplify = TRUE`?

```
    # Fetch wavenumbers
    wns <- lapply(
        res,
        function(x) round(x$wavenumbers, digits = 0)
     )
```

Concatenating from a list of single single spectra to a matrix would require resampling to work properly. By rounding we loose precision, and if the resolution or the range of spectra is different the simplifed output does not work. 

The sole purpose of the package is reading OPUS binary files, so therefore simplify in cases where resampling is required seems a bit beyond scope to me. There is for example prospectr, so the user can do this step this way. I'm for example interested in robust automated pipelines. There, signalling warnings instead of stopping or inducing different behavior if spectra are not compatible seems a bit odd (by different behavior I mean that we would return full list output with 1 spectra row per sample).

**Comment by pierreroudier** [comment]
> The initial idea why I included the `wavenumbers` vector was because it's not really straightforward to deal with them only as column names of matrices and data.frames. What's the rationale behind rounding wavenumbers when `simplify = TRUE`?
> 

The rationale is to provide users a quick way to assemble a spectral matrix, ready for statistical inference, eg:

```
# Get a list of OPUS file names to read
my_files <- list.files(path = "path/to/spectra/", pattern =  "^.*\\.0$", full.names = TRUE)

# Assemble spectra matrix
spec <- opus_read(my_files, simplify = TRUE)

# Returns a N x P matrix
spec
```

> Concatenating from a list of single single spectra to a matrix would require resampling to work properly. By rounding we loose precision, and if the resolution or the range of spectra is different the simplifed output does not work.
> 

Yes, so what I found is that even for spectra collected using the same machine/the same day/etc, wavenumbers tend to vary a tiny bit (+/- 1 cm$^-1$) -- they are never completely identical. That rounding is basically a brute force solution to collate those spectral files into a matrix, which makes the assumption that this 1 cm$^-1$ rounding has little to no impact.

Now, I've mostly worked with vis-NIR data, which returns nice, consistent wavelengths, which is why I tried to implement this I suppose.

But of course, you are right, to do things properly, we should probably resample I'll try to see what the impact on the spectra actually is. 

> The sole purpose of the package is reading OPUS binary files, so therefore simplify in cases where resampling is required seems a bit beyond scope to me. There is for example prospectr, so the user can do this step this way. I'm for example interested in robust automated pipelines. There, signalling warnings instead of stopping or inducing different behavior if spectra are not compatible seems a bit odd (by different behavior I mean that we would return full list output with 1 spectra row per sample).

That said, a couple of things:

-  I doubt you'd need prospectr to do such minor resampling (that's not interpolation), so `stats::approx` should be sufficient (and computationally inexpensive). 
-  If you wanted to be really robust, you'd probably stick to the default `simplify = FALSE`, and return the entire metadata, including the actual wavenumbers for each spectra.  

In terms of user experience, the appeal of being able to use `opus_read` on a vector of file names, and returning a matrix, is simplicity: it means you do not have to know and use `lapply` to "massage" the output of `opus_read` before you can use it.

**Comment by pierreroudier** [comment]
Update: I can confirm the resampling is fast -- but also does very little.

```
library(opusreader)

# Read spectra
spec <- opus_read(opus_file())

# Extract wavenumbers
wn <- spec$wavenumbers -> wn

# Here we store the "rounded" wavenumbers
wr<- round(wn, digits = 0) -> wr

# This is the proper resampling of the spectra to the "rounded" wavenumbers
resamp <- approx(x = wn, y = spec$spc, xout = wr, method = "linear")

# Creating a matrix comparing original and resampled spectra
comp <- cbind(as.numeric(spec$spc), resamp$y) 

# Generate summary of the differences between reference and resampled spectra
summary(apply(comp, 1, diff))

      Min.    1st Qu.     Median       Mean    3rd Qu.       Max. 
-3.175e-03 -2.645e-05  9.000e-08  2.027e-06  2.796e-05  2.323e-03
```

**Comment by pierreroudier** [comment]
Commit https://github.com/pierreroudier/opusreader/commit/3ad55474fde2f10aff26a9d210baadfac4184a03 implements proper resampling using linear interpolation when using `simplify = TRUE` (not the default behaviour).

Compatibility in wavenumbers lengths is also checked now.

Default behaviour (`simplify = FALSE`) still returns the full list, and does not round up wavenumber values, or resample spectral values. 

I have also plotted the difference between the original spectra, and a resampled spectra recorded at rounded wavenumbers. The difference is minimal:

![Difference between "raw" spectra, and spectra resampled at rounded up wavenumbers](https://user-images.githubusercontent.com/515259/116339938-6fa75300-a832-11eb-945e-5a0d703be1b2.png)

Original spectra:

![Original spectra](https://user-images.githubusercontent.com/515259/116340137-c3b23780-a832-11eb-9a8c-9fc1a5371b6f.png)

**Comment by philipp-baumann** [comment]
> > The initial idea why I included the `wavenumbers` vector was because it's not really straightforward to deal with them only as column names of matrices and data.frames. What's the rationale behind rounding wavenumbers when `simplify = TRUE`?
> 
> The rationale is to provide users a quick way to assemble a spectral matrix, ready for statistical inference, eg:
> 
> ```
> # Get a list of OPUS file names to read
> my_files <- list.files(path = "path/to/spectra/", pattern =  "^.*\\.0$", full.names = TRUE)
> 
> # Assemble spectra matrix
> spec <- opus_read(my_files, simplify = TRUE)
> 
> # Returns a N x P matrix
> spec
> ```

OK, you got me, reconsidering this choice ;-)

> 
> > Concatenating from a list of single single spectra to a matrix would require resampling to work properly. By rounding we loose precision, and if the resolution or the range of spectra is different the simplifed output does not work.
> 
> Yes, so what I found is that even for spectra collected using the same machine/the same day/etc, wavenumbers tend to vary a tiny bit (+/- 1 cm$^-1$) -- they are never completely identical. That rounding is basically a brute force solution to collate those spectral files into a matrix, which makes the assumption that this 1 cm$^-1$ rounding has little to no impact.
> 
> Now, I've mostly worked with vis-NIR data, which returns nice, consistent wavelengths, which is why I tried to implement this I suppose.

My guess is this has more to do with the internal procedures of the FTIR spectrometer at hand in general. If the values for the X-units are constant, resampling was done after reconstructing the spectra prior export. I don't know whether manufacturers always declare it. As an example, for Neospectra from Si-Ware Systems we are currently testing, there is an option to set fixed linear output in wavenumbers (which is of course non-linear in wavenlengths).

>

**Comment by philipp-baumann** [comment]
Tiny one missing, will do a short pull request.

``` r
library("opusreader")

fp <- opus_file()
s_default <- opus_read(rep(fp, 10))
s_simplified <- opus_read(rep(fp, 10), simplify = TRUE)

dim(s_default[[1]]$spc)
#> [1]    1 4819
dim(s_simplified$spectra)
#> [1]   10 4819
colnames(s_simplified$spectra)[1:5]
#> NULL
colnames(s_default[[1]]$spc)[1:5]
#> [1] "7498.3" "7496.9" "7495.4" "7494"   "7492.6"
```

<sup>Created on 2021-04-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by pierreroudier** [comment]
Closing as this issue was addressed by https://github.com/pierreroudier/opusreader/commit/3ad55474fde2f10aff26a9d210baadfac4184a03 and PR https://github.com/pierreroudier/opusreader/pull/5
