### ISSUE TITLE
`opus_read()`: default output to named list when `file` are multiple files

### ISSUE THREAD

**Issue by philipp-baumann** [pierreroudier/opusreader#6]
Currently, `opus_read()` returns a nested list of spectra elements, when `simplify = FALSE` and `file` are paths to multiple OPUS binary files:

``` r
library("opusreader")

fp <- opus_file()
s_default <- opus_read(rep(fp, 10L))
s_default[[1]]$metadata
#>                     unique_id sample_id rep_no        date_time_sm
#> 1 SB9742A_2020-05-11 09:09:55   SB9742A     NA 2020-05-11 09:09:55
#>          date_time_rf                     sample_name instr_name_range
#> 1 2020-05-11 08:59:44 SB9742A;Marmar;;SMAP QUICK;Soil    TENSOR II-MIR
#>   resolution_wn result_spc beamspl laser_wn   spc_in_file zero_filling
#> 1             4        RFL     KBr 11729.24 ScSm;ScRf;spc            2
#>   temp_scanner_sm temp_scanner_rf hum_rel_sm hum_rel_rf hum_abs_sm hum_abs_rf
#> 1            24.1            24.4         10         NA         NA         NA
names(s_default)
#> NULL
```

<sup>Created on 2021-05-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

The file names are in the metadata elements, but I'd like to have support named outputs of `opus_read()` if more than one file is read (analogous to `simplerspec::read_opus_univ()`). This would give further flexibility to user how to parse from binary and further process spectra in R.

It would be possible to add full paths instead or control the names of the individual spectra via a further argument, e..g when spectra are not in working directory (e.g. reference spectra). I'm not so sure about this option. This would allow for reading quality control samples named identially but read at different time point. I can draft something and do a pull request. @pierreroudier do you have any further thoughts on this?

**Comment by pierreroudier** [comment]
I have intentionally not implemented this for several reasons:

- it would break if you read the same file more than once: arguably, it is an exotic issue, but for example one couldn't do `opus_read(rep(opus_file(), times = 2))`
- the file name info is present in R when you read the files anyway, and can be pasted into the object later

But happy to discuss!

**Comment by pierreroudier** [comment]
@philipp-baumann I am closing the issue, following our discussion, but happy to re-open it if I have misunderstood.
