### ISSUE TITLE
Keep track of changes and document versioning in `NEWS.md`

### ISSUE THREAD

**Issue by philipp-baumann** [pierreroudier/opusreader#9]
I suggest that we document changes during development and mark important features or bug fixes in production releases. I find [{fledge}](https://krlmlr.github.io/fledge/) epic to assist in this process and track the steps done via commit messages, so that they can be incorporated automatically in sections and modified later. This enhances trust of users and facilitates adoption and bug fixing + getting more brains working on reverse engineering Bruker OPUS.

**Comment by pierreroudier** [comment]
Excellent, I did not know about the package!

Done in https://github.com/pierreroudier/opusreader/commit/2f0014faf04a430be493fa49427da1efd0d06eeb
